### PR TITLE
Added-Accessibility-Personal-Portfolio

### PR DESCRIPTION
**Pull request by moise10r**
## Accessibility problems:

- Page titles: no issues found.
- Image text alternatives: issues found.
- Text heading: issues found.
- Color contrast: issues found.  
- Resize: no issues found.
- Interaction: issues found.
- Moving content: no issues found.
- multimedia: no issues found.
- The basic structure of the page: no issues found. 

## Accessibility solutions provided:

- Image text alternatives: We solved the image text alternatives problem by adding the " alt " attribute on the img tag.
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L162
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L162-L164
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L185
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L193-L195
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L218
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L226-L228
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L251
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L259-L261
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L398-L406
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L420-L428
    - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L442-L450

- text heading: text headings accessibility issues were fixed by changing the order of the heading Tags on the page.
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L390
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L412
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L434
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L459
  

- interaction: We fixed the Interaction issues by adding focus, active pseudo-elements to all buttons, and label tags before each 
input field.
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L472-L499
  - https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/style/style.css#L63-L136

The color contrast issues could not be fixed because the project followed the design provided by microverse on Figma

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @moise10r @olawale-o, 

Good job so far, you did some changes in order to make accessible your website!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] You need to improve your report (in the PR description) and follow the structure in your requirements, this means, adding a bullet point list in addition to your resume. Double-check [your requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md). Remember to put in the list links to the changes you made on your files.

image


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

you can do it

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by moise10r** [comment]
*Hey **mricanho,*

We need to be clarified on the requirements of this task, so are we
supposed to make an inline review on each line of code that we need to
improve, in the case of color contrast accessibility issue we can not
improve that. because the colors were provided on the template given to us
by microverse on figma.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
15/06/21,
17:19:48

Le mar. 15 juin 2021 à 16:11, Miguel Ricaño ***@***.***> a
écrit :

**Review by henatan99 — CHANGES_REQUESTED** [review]
Hi @moise10r , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

- [ ] Whenever issues are found and changes are introduced describe the changes made briefly and in short.
- [ ] You need to link your description to the related changes made in your code. You can use the permalink and attach the link with the description. See the below example and screenshot. 
[PermaLink](https://github.com/moise10r/Personal_Portfolio/blob/66e71172c11ed28ddc7e87a59efeb1f194187445/index.html#L5-L11) 
Screenshot from 2021-06-16 02-08-14


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by teekaytech — APPROVED** [review]
## Status: Approved :green_circle: 

### Congratulations @username :tada: :clinking_glasses: 

**Your project is complete! 
Thank you for adding the lines of code where you've made your changes :handshake: 
This is a convenient point to merge :rocket:**

- - - - - -

**_Feel free to leave any questions or comments in the PR thread if something is not 100% clear._**

Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
_Cheers,_
**[Taofeek Olalere](https://github.com/teekaytech)**
__Happy Coding :smiley:__

**Pull request merged**
